### ISSUE TITLE
Android真机微信上文字模糊

### ISSUE THREAD

**Issue by ghost** [finscn/pixi.js#6]
你好。
**你是否遇到过文字在Android系统下模糊的问题。**
我设置了PIXI.settings.resolution为系统的pixel ratio。
- 在Android浏览器环境正常。
- 在微信开发者工具正常。
- 在IOS正常。
就是Android的真机微信中文字模糊。

**Comment by jonlepage** [comment]
did you try to turn off  `antialias: false` ?

```javascript
class _app extends PIXI.Application {
    constructor() {
        super({
            antialias: false, // remove text blur 
          });
    };
```

**Comment by ghost** [comment]
@djmisterjon 
Thank you for your answer. 
It's not a solution for me. Finally, I fixed this by setting a large font size, then reduce the `scale`, although it's just a problem on wechat for android.
