### ISSUE TITLE
How to use Animation.js?

### ISSUE THREAD

**Issue by FlemmingH** [finscn/pixi.js#7]
I'm not sure how to use Animation.js. My animation texture is loaded from a spritesheet with 100 frames. Where is the sprite texture supposed to be assigned from? 
This isn't working:

`           var sprite = new PIXI.Sprite(lightTextures[0]);
            var candle = new PIXI.Animation(lightTextures);
            candle.bind(sprite);
            candle.x = x;
            candle.y = y;
            stage.addChild(candle);
            candle.gotoAndPlay(Math.floor(Math.random() * 50));`

Adding the sprite instead of the animation doesn't work to.
I know the the animation is ok, because it works in the original pixi. Could you give me an example on how to use it and how to scale it?

**Comment by finscn** [comment]
```
    var sprite = new PIXI.Sprite(PIXI.Texture.EMPTY);

    var anim = new PIXI.extensions.Animation(frames, duration);

    anim.bind(sprite, animBindName);

```
animBindName is a string.

e.g. ,  animBindName = "walk"

```
// jump to 0 frame , and start to play
sprite.walk.gotoAndPlay(0)

// update walk-animation, must call update() in game-loop
sprite.walk.update(timeStep);

// jump to 0 frame , and pstop
sprite.walk.gotoAndStop(0)

sprite.walk.pause()  // pause animation

sprite.walk.play()  // play animation
```
If not set animBindName, the defalut animBindName will be "anim".
```
sprite.anim.update(timeStep);

```

**Comment by finscn** [comment]
the `frames ` is like  `textures` of `AnimatedSprite(textures)`.

**Comment by FlemmingH** [comment]
Ok, so `frames` are the loaded spritesheet. But what are `Texture.EMPTY` ?

**Comment by finscn** [comment]
PIXI.Texture.EMPTY .
```new PIXI.Sprite(PIXI.Texture.EMPTY)``` will create a sprite without any texture.
Because the informations of textures have been defined in  animation.

**Comment by FlemmingH** [comment]
```
var animBindName="burn";
var sprite = new PIXI.Sprite(PIXI.Texture.EMPTY);
var anim = new PIXI.extensions.Animation(lightTextures, 3000);
anim.bind(sprite, animBindName);
sprite.burn.gotoAndPlay(0);
```

Then i get `TypeError: sprite.burn is undefined`. Without the `bind` i get `TypeError: sprite.anim is undefined`.

**Comment by finscn** [comment]
@FlemmingH  ,  do you use the last version ?

**Comment by FlemmingH** [comment]
I used 4.8.6. Now i upgraded to 4.8.7 and i'm getting `PIXI.lights is undefined`. Actually the reason why i'm using your pixi fork is because i'm convinced that your lightning code outperforms pixi-lights. I used the code from http://proclive.io/lights-in-pixi-js/ , but i wan't to add some animation to it.

**Comment by finscn** [comment]
@FlemmingH  , in the last pixi of my fork ,  I've moved the lighting plugin into a standalone project: pixi-lighting  https://github.com/finscn/pixi-lighting.

And I changed the namespace from  PIXI.lights to PIXI.lighting .

If you don't like it , you could checkout  ba31f3 .

**Comment by FlemmingH** [comment]
Ok , i would like to try it out! Do you got a compiled version of pixi-lighting?

**Comment by finscn** [comment]
I've committed compiled version : https://github.com/finscn/pixi-lighting/tree/master/dist

**Comment by FlemmingH** [comment]
Thank's!
